// Construction-store category taxonomy. Data only; rules live in classify.mjs.
// Keywords are matched against normalized names on word boundaries; multi-word
// phrases score higher than single words (SC-2). `strong` lists unambiguous
// single trade terms (ISMB, MCB, TMT…) that weigh as much as a two-word phrase. No phrase may appear in two
// categories (SC-9).

const base = { altUoms: [], kind: 'consumable', returnable: false, hazardous: false,
               restricted: false, issueToPerson: false, required: [] };

export const TAXONOMY = [
  { ...base, code: 'CEM', name: 'Cement & Binders', baseUom: 'bag', altUoms: ['kg', 't'],
    required: ['cementType'],
    keywords: ['cement', 'white cement', 'hydrated lime', 'lime powder',
               'fly ash', 'micro silica'],
    strong: ['opc', 'ppc', 'psc', 'ggbs'] },
  { ...base, code: 'CON', name: 'Ready-mix Concrete', baseUom: 'm3', required: ['concreteGrade'],
    keywords: ['ready mix', 'readymix', 'ready mix concrete', 'concrete', 'screed concrete'],
    strong: ['rmc', 'pcc'],
    patterns: [['concrete-grade', /\bm ?(?:7\.5|10|15|20|25|30|35|40|45|50|60)\b/]] },
  { ...base, code: 'AGG', name: 'Aggregates & Sand', baseUom: 'm3', altUoms: ['t', 'cft'],
    keywords: ['sand', 'm sand', 'river sand', 'p sand', 'plaster sand', 'coarse aggregate', 'fine aggregate', 'gravel', 'blue metal', 'crushed stone',
               'quarry dust', 'stone dust', 'boulders', 'soil'],
    strong: ['gsb', 'wmm', 'msand', 'jelly', 'aggregate', 'murrum'] },
  { ...base, code: 'STL', name: 'Steel & Reinforcement', baseUom: 'kg', altUoms: ['t'],
    required: ['sizeMm', 'steelGrade'],
    keywords: ['reinforcement', 'reinforcement bar', 'tor steel', 'binding wire',
               'ms angle', 'ms channel', 'ms plate', 'ms pipe', 'ms flat', 'ms sheet', 'ms bar',
               'i beam', 'steel', 'hollow section', 'shs', 'rhs', 'chequered plate'],
    strong: ['tmt', 'rebar', 'ismb', 'ismc'],
    patterns: [['fe-grade', /\bfe ?\d{3}d?\b/]] },
  { ...base, code: 'MAS', name: 'Masonry', baseUom: 'pcs',
    keywords: ['red brick', 'fly ash brick', 'aac block', 'solid block',
               'hollow block', 'concrete block', 'paver block', 'kerb stone', 'block'],
    strong: ['aac', 'brick', 'bricks', 'paver'] },
  { ...base, code: 'FRM', name: 'Formwork & Timber', baseUom: 'pcs', altUoms: ['sqm'], returnable: true,
    keywords: ['shuttering ply', 'film faced', 'props',
               'acrow prop', 'span', 'spans', 'timber', 'batten', 'wooden', 'scaffolding',
               'u jack', 'base jack', 'shuttering plate'],
    strong: ['cuplock', 'plywood', 'acrow', 'formwork', 'shuttering'] },
  { ...base, code: 'ELE', name: 'Electrical', baseUom: 'pcs', altUoms: ['m', 'roll', 'coil'],
    keywords: ['cable', 'wire', 'copper wire', 'fr wire', 'armoured cable', 'flexible cable',
               'switch', 'socket', 'conduit', 'conduit pipe',
               'db box', 'distribution board', 'lug', 'gland', 'led', 'tube light', 'junction box',
               'modular box', 'earthing'],
    strong: ['mcb', 'rccb', 'elcb', 'mccb', 'frls'],
    patterns: [['sq-mm', /\d(?:\.\d+)? ?sq mm\b/]] },
  { ...base, code: 'PLB', name: 'Plumbing & Sanitary', baseUom: 'pcs', altUoms: ['m', 'length'],
    required: ['sizeMm'],
    keywords: ['pvc', 'gi pipe', 'pipe', 'elbow', 'tee', 'reducer',
               'coupling', 'ball valve', 'gate valve', 'valve', 'tap', 'bib cock',
               'wash basin', 'wc', 'water closet', 'floor trap', 'nahani trap', 'solvent cement',
               'water tank', 'plumbing'],
    strong: ['cpvc', 'upvc', 'hdpe', 'swr', 'faucet'] },
  { ...base, code: 'FIN', name: 'Finishes & Tiles', baseUom: 'sqm', altUoms: ['box', 'pcs', 'bag'],
    keywords: ['tile', 'tiles', 'ceramic', 'kota stone',
               'wall putty', 'plaster of paris', 'pop', 'gypsum board',
               'tile adhesive', 'tile grout', 'skirting', 'false ceiling'],
    strong: ['vitrified', 'putty', 'granite', 'marble', 'gypsum'] },
  { ...base, code: 'PNT', name: 'Paints & Chemicals', baseUom: 'l', altUoms: ['kg', 'bucket'],
    hazardous: true,
    keywords: ['paint', 'turpentine',
               'plasticizer', 'curing compound', 'sealant',
               'bituminous', 'membrane', 'chemical', 'dr fixit', 'shutter oil',
               'release agent'],
    strong: ['primer', 'emulsion', 'enamel', 'distemper', 'thinner', 'waterproofing', 'admixture', 'epoxy', 'bitumen'] },
  { ...base, code: 'HRD', name: 'Hardware, Fasteners & Abrasives', baseUom: 'pcs', altUoms: ['box', 'kg'],
    keywords: ['bolt', 'nut', 'screw', 'nail', 'nails', 'wire nails', 'wire nail', 'anchor', 'anchor fastener', 'washer',
               'cutting disc', 'cutting wheel', 'grinding disc', 'grinder disc', 'grinder wheel',
               'grinding wheel', 'drill bit', 'hacksaw blade', 'welding rod', 'electrode',
               'sand paper', 'emery', 'cable tie', 'tie wire'],
    strong: ['fastener', 'rivet', 'hinge'] },
  { ...base, code: 'PPE', name: 'Safety & PPE', baseUom: 'pcs', issueToPerson: true,
    keywords: ['safety helmet', 'safety shoes', 'hand gloves',
               'reflective vest', 'safety vest', 'jacket', 'safety harness',
               'full body harness', 'ear plug', 'ear muff', 'mask', 'face shield',
               'safety net', 'ppe'],
    strong: ['helmet', 'gloves', 'goggles', 'harness', 'gumboot'] },
  { ...base, code: 'TLS', name: 'Tools & Equipment', baseUom: 'pcs', kind: 'asset', returnable: true,
    keywords: ['drill machine', 'hammer drill', 'rotary hammer', 'angle grinder', 'cutter', 'cutting machine', 'tile cutter', 'hammer', 'sledge hammer', 'wrench', 'plier', 'screwdriver', 'measuring tape', 'spirit level', 'level',
               'ladder', 'needle vibrator', 'concrete mixer',
               'mixer machine', 'welding machine', 'generator', 'pump', 'dewatering pump',
               'total station', 'auto level', 'machine', 'tool', 'kit'],
    strong: ['grinder', 'vibrator', 'wheelbarrow', 'spanner', 'trowel'] },
  { ...base, code: 'FUL', name: 'Fuel & Lubricants', baseUom: 'l', altUoms: ['barrel', 'kg'],
    hazardous: true, restricted: true,
    keywords: ['engine oil', 'hydraulic oil', 'gear oil',
               'fuel'],
    strong: ['diesel', 'hsd', 'petrol', 'kerosene', 'grease', 'lubricant'] },
];
